%ignore intToPurpose(dpp_identity_identity_public_key_purpose_Purpose);
%ignore intToSecurityLevel(dpp_identity_identity_public_key_security_level_SecurityLevel);
%ignore intToKeyType(dpp_identity_identity_public_key_key_type_KeyType);