%ignore purpose_AUTHENTICATION_ctor();
%rename(Purpose) dpp_identity_identity_public_key_purpose_Purpose;
%rename(KeyType) dpp_identity_identity_public_key_key_type_KeyType;
%rename(SecurityLevel) dpp_identity_identity_public_key_security_level_SecurityLevel;

%rename(MEDIUM) dpp_identity_identity_public_key_security_level_SecurityLevel_MEDIUM;
%rename(MASTER) dpp_identity_identity_public_key_security_level_SecurityLevel_MASTER;
%rename(CRITICAL) dpp_identity_identity_public_key_security_level_SecurityLevel_CRITICAL;
%rename(HIGH) dpp_identity_identity_public_key_security_level_SecurityLevel_HIGH;

%rename(AUTHENTICATION) dpp_identity_identity_public_key_purpose_Purpose_AUTHENTICATION;
%rename(ENCRYPTION) dpp_identity_identity_public_key_purpose_Purpose_ENCRYPTION;
%rename(DECRYPTION) dpp_identity_identity_public_key_purpose_Purpose_DECRYPTION;
%rename(WITHDRAW) dpp_identity_identity_public_key_purpose_Purpose_WITHDRAW;
%rename(SYSTEM) dpp_identity_identity_public_key_purpose_Purpose_SYSTEM;
%rename(VOTING) dpp_identity_identity_public_key_purpose_Purpose_VOTING;

%rename (ECDSA_SECP256K1) dpp_identity_identity_public_key_key_type_KeyType_ECDSA_SECP256K1;
%rename (BLS12_381) dpp_identity_identity_public_key_key_type_KeyType_BLS12_381;
%rename (ECDSA_HASH160) dpp_identity_identity_public_key_key_type_KeyType_ECDSA_HASH160;
%rename (BIP13_SCRIPT_HASH) dpp_identity_identity_public_key_key_type_KeyType_BIP13_SCRIPT_HASH;
%rename (EDDSA_25519_HASH160) dpp_identity_identity_public_key_key_type_KeyType_EDDSA_25519_HASH160;