/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.platform.sdk;

import org.dashj.platform.sdk.base.BaseObject;

public class ContractBounds extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ContractBounds(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContractBounds obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_ContractBounds(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void setTag(ContractBounds_Tag value) {
    exampleJNI.ContractBounds_tag_set(swigCPtr, this, value.swigValue());
  }

  public ContractBounds_Tag getTag() {
    return ContractBounds_Tag.swigToEnum(exampleJNI.ContractBounds_tag_get(swigCPtr, this));
  }

  public void setSingle_contract(SingleContractStruct value) {
    exampleJNI.ContractBounds_single_contract_set(swigCPtr, this, SingleContractStruct.getCPtr(value), value);
  }

  public SingleContractStruct getSingle_contract() {
    long cPtr = exampleJNI.ContractBounds_single_contract_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SingleContractStruct(cPtr, false);
  }

  public void setSingle_contract_document_type(SingleContractDocumentTypeStruct value) {
    exampleJNI.ContractBounds_single_contract_document_type_set(swigCPtr, this, SingleContractDocumentTypeStruct.getCPtr(value), value);
  }

  public SingleContractDocumentTypeStruct getSingle_contract_document_type() {
    long cPtr = exampleJNI.ContractBounds_single_contract_document_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SingleContractDocumentTypeStruct(cPtr, false);
  }

  public ContractBounds(Identifier id) {
    this(exampleJNI.new_ContractBounds__SWIG_0(Identifier.getCPtr(id), id), true);
  }

  public ContractBounds(Identifier id, String document_type) {
    this(exampleJNI.new_ContractBounds__SWIG_1(Identifier.getCPtr(id), id, document_type), true);
  }

}
