/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class dpp_identity_identity_public_key_KeyCount extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected dpp_identity_identity_public_key_KeyCount(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dpp_identity_identity_public_key_KeyCount obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_dpp_identity_identity_public_key_KeyCount(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void set_0(KeyID value) {
    exampleJNI.dpp_identity_identity_public_key_KeyCount__0_set(swigCPtr, this, KeyID.getCPtr(value), value);
  }

  public KeyID get_0() {
    long cPtr = exampleJNI.dpp_identity_identity_public_key_KeyCount__0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new KeyID(cPtr, false);
  }

}
