/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.platform.sdk;

public final class Identity_Tag {
  public final static Identity_Tag IdentityV0Type = new Identity_Tag("IdentityV0Type");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Identity_Tag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Identity_Tag.class + " with value " + swigValue);
  }

  private Identity_Tag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Identity_Tag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Identity_Tag(String swigName, Identity_Tag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Identity_Tag[] swigValues = { IdentityV0Type };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

