/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class IdentityPublicKeyV0 extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IdentityPublicKeyV0(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IdentityPublicKeyV0 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_IdentityPublicKeyV0(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void setId(KeyID value) {
    exampleJNI.IdentityPublicKeyV0_id_set(swigCPtr, this, KeyID.getCPtr(value), value);
  }

  public KeyID getId() {
    long cPtr = exampleJNI.IdentityPublicKeyV0_id_get(swigCPtr, this);
    return (cPtr == 0) ? null : new KeyID(cPtr, false);
  }

  public void setContract_bounds(ContractBounds value) {
    exampleJNI.IdentityPublicKeyV0_contract_bounds_set(swigCPtr, this, ContractBounds.getCPtr(value), value);
  }

  public ContractBounds getContract_bounds() {
    long cPtr = exampleJNI.IdentityPublicKeyV0_contract_bounds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ContractBounds(cPtr, false);
  }

  public void setRead_only(boolean value) {
    exampleJNI.IdentityPublicKeyV0_read_only_set(swigCPtr, this, value);
  }

  public boolean getRead_only() {
    return exampleJNI.IdentityPublicKeyV0_read_only_get(swigCPtr, this);
  }

  public void setData(BinaryData value) {
    exampleJNI.IdentityPublicKeyV0_data_set(swigCPtr, this, BinaryData.getCPtr(value), value);
  }

  public BinaryData getData() {
    long cPtr = exampleJNI.IdentityPublicKeyV0_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new BinaryData(cPtr, false);
  }

  public void setDisabled_at(TimestampMillis value) {
    exampleJNI.IdentityPublicKeyV0_disabled_at_set(swigCPtr, this, TimestampMillis.getCPtr(value), value);
  }

  public TimestampMillis getDisabled_at() {
    long cPtr = exampleJNI.IdentityPublicKeyV0_disabled_at_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TimestampMillis(cPtr, false);
  }

  public IdentityPublicKeyV0(KeyID keyId, Purpose purpose, SecurityLevel securityLevel, ContractBounds contract_bounds, KeyType key_type, boolean read_only, BinaryData data, TimestampMillis disabled_at) {
    this(exampleJNI.new_IdentityPublicKeyV0(KeyID.getCPtr(keyId), keyId, purpose.swigValue(), securityLevel.swigValue(), ContractBounds.getCPtr(contract_bounds), contract_bounds, key_type.swigValue(), read_only, BinaryData.getCPtr(data), data, TimestampMillis.getCPtr(disabled_at), disabled_at), true);
  }

  public KeyType getKeyType() {
    return KeyType.swigToEnum(exampleJNI.IdentityPublicKeyV0_getKeyType(swigCPtr, this));
  }

  public Purpose getPurpose() {
    return Purpose.swigToEnum(exampleJNI.IdentityPublicKeyV0_getPurpose(swigCPtr, this));
  }

  public SecurityLevel getSecurityLevel() {
    return SecurityLevel.swigToEnum(exampleJNI.IdentityPublicKeyV0_getSecurityLevel(swigCPtr, this));
  }

}
