/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.platform.sdk;

import org.dashj.platform.sdk.base.BaseObject;

public class IdentityPublicKey extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IdentityPublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IdentityPublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_IdentityPublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  static public class V0_Body extends BaseObject {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected V0_Body(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(V0_Body obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          exampleJNI.delete_IdentityPublicKey_V0_Body(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    protected long getCPointer() {
      return swigCPtr;
    }
  
    public void set_0(IdentityPublicKeyV0 value) {
      exampleJNI.IdentityPublicKey_V0_Body__0_set(swigCPtr, this, IdentityPublicKeyV0.getCPtr(value), value);
    }
  
    public IdentityPublicKeyV0 get_0() {
      long cPtr = exampleJNI.IdentityPublicKey_V0_Body__0_get(swigCPtr, this);
      return (cPtr == 0) ? null : new IdentityPublicKeyV0(cPtr, false);
    }
  
  }

  public void setTag(IdentityPublicKey.Tag value) {
    exampleJNI.IdentityPublicKey_tag_set(swigCPtr, this, value.swigValue());
  }

  public IdentityPublicKey.Tag getTag() {
    return IdentityPublicKey.Tag.swigToEnum(exampleJNI.IdentityPublicKey_tag_get(swigCPtr, this));
  }

  public void setV0(IdentityPublicKey.V0_Body value) {
    exampleJNI.IdentityPublicKey_v0_set(swigCPtr, this, IdentityPublicKey.V0_Body.getCPtr(value), value);
  }

  public IdentityPublicKey.V0_Body getV0() {
    long cPtr = exampleJNI.IdentityPublicKey_v0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IdentityPublicKey.V0_Body(cPtr, false);
  }

  public IdentityPublicKey(IdentityPublicKeyV0 ipkv0) {
    this(exampleJNI.new_IdentityPublicKey(IdentityPublicKeyV0.getCPtr(ipkv0), ipkv0), true);
  }

  public final static class Tag {
    public final static IdentityPublicKey.Tag V0 = new IdentityPublicKey.Tag("V0");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Tag swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Tag.class + " with value " + swigValue);
    }

    private Tag(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Tag(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Tag(String swigName, Tag swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Tag[] swigValues = { V0 };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
