/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.platform.sdk;

import org.dashj.platform.sdk.base.BaseObject;

public class KeyCount extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KeyCount(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KeyCount obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_KeyCount(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public KeyCount() {
    this(exampleJNI.new_KeyCount__SWIG_0(), true);
  }

  public KeyCount(int value) {
    this(exampleJNI.new_KeyCount__SWIG_1(value), true);
  }

  public int toInt() {
    return exampleJNI.KeyCount_toInt(swigCPtr, this);
  }

  public boolean objectEquals(KeyCount other) {
    return exampleJNI.KeyCount_objectEquals(swigCPtr, this, KeyCount.getCPtr(other), other);
  }

}
