/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.platform.sdk;

import org.dashj.platform.sdk.base.BaseObject;

public class KeyID extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KeyID(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KeyID obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_KeyID(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public KeyID(int id) {
    this(exampleJNI.new_KeyID(id), true);
  }

  public int toInt() {
    return exampleJNI.KeyID_toInt(swigCPtr, this);
  }

  public boolean objectEquals(KeyID other) {
    return exampleJNI.KeyID_objectEquals(swigCPtr, this, KeyID.getCPtr(other), other);
  }

}
