/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dashj.platform.sdk;

import org.dashj.platform.sdk.base.BaseObject;

public class SWIGTYPE_p_p_dpp_identity_identity_public_key_IdentityPublicKey extends BaseObject {
  private transient long swigCPtr;

  protected SWIGTYPE_p_p_dpp_identity_identity_public_key_IdentityPublicKey(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_p_dpp_identity_identity_public_key_IdentityPublicKey() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_p_dpp_identity_identity_public_key_IdentityPublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected long getCPointer() {
    return swigCPtr;
  }
}

