/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class BinaryData extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BinaryData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BinaryData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_BinaryData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public void set_0(byte[] value) {
    exampleJNI.BinaryData__0_set(swigCPtr, this, value);
  }

  public byte[] get_0() {
    return exampleJNI.BinaryData__0_get(swigCPtr, this);
  }

  public BinaryData(byte[] o_0) {
    this(exampleJNI.new_BinaryData(o_0), true);
  }

}
