/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

public final class KeyType {
  public final static KeyType ECDSA_SECP256K1 = new KeyType("ECDSA_SECP256K1", exampleJNI.ECDSA_SECP256K1_get());
  public final static KeyType BLS12_381 = new KeyType("BLS12_381", exampleJNI.BLS12_381_get());
  public final static KeyType ECDSA_HASH160 = new KeyType("ECDSA_HASH160", exampleJNI.ECDSA_HASH160_get());
  public final static KeyType BIP13_SCRIPT_HASH = new KeyType("BIP13_SCRIPT_HASH", exampleJNI.BIP13_SCRIPT_HASH_get());
  public final static KeyType EDDSA_25519_HASH160 = new KeyType("EDDSA_25519_HASH160", exampleJNI.EDDSA_25519_HASH160_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static KeyType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + KeyType.class + " with value " + swigValue);
  }

  private KeyType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private KeyType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private KeyType(String swigName, KeyType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static KeyType[] swigValues = { ECDSA_SECP256K1, BLS12_381, ECDSA_HASH160, BIP13_SCRIPT_HASH, EDDSA_25519_HASH160 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

