/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.dash.sdk;

import org.dash.sdk.base.BaseObject;

public class MemoryFactory extends BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MemoryFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MemoryFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_MemoryFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected long getCPointer() {
    return swigCPtr;
  }

  public static MemoryFactory getInstance() {
    long cPtr = exampleJNI.MemoryFactory_getInstance();
    return (cPtr == 0) ? null : new MemoryFactory(cPtr, false);
  }

  public MemoryFactory() {
    this(exampleJNI.new_MemoryFactory(), true);
  }

  public long size() {
    return exampleJNI.MemoryFactory_size(swigCPtr, this);
  }

  public SWIGTYPE_p_void alloc(long size) {
    long cPtr = exampleJNI.MemoryFactory_alloc__SWIG_0(swigCPtr, this, size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public String clone(String str) {
    return exampleJNI.MemoryFactory_clone(swigCPtr, this, str);
  }

  public SWIGTYPE_p_void alloc(SWIGTYPE_p_void root, long size) {
    long cPtr = exampleJNI.MemoryFactory_alloc__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(root), size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void destroy(SWIGTYPE_p_void root, SWIGTYPE_p_void memory) {
    exampleJNI.MemoryFactory_destroy__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(root), SWIGTYPE_p_void.getCPtr(memory));
  }

  public void destroy(SWIGTYPE_p_void root) {
    exampleJNI.MemoryFactory_destroy__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(root));
  }

  public void destroyItem(SWIGTYPE_p_void item) {
    exampleJNI.MemoryFactory_destroyItem(swigCPtr, this, SWIGTYPE_p_void.getCPtr(item));
  }

}
